pipeline {
    agent any
   
    stages {
        stage ('Use summon to pull password') {
            steps {
                sh "summon -f secrets.yml bash pullPasswordSUMMON.sh"
            }
        }
    }
}