---
# defaults file for machinePrep

# defaults file for dockerConfig
docker_edition: 'ce'
docker_package: "docker-{{ docker_edition }}"

#docker redhat/centos repo
docker_yum_repo_url: https://download.docker.com/linux/{{ (ansible_distribution == "Fedora") | ternary("fedora","centos") }}/docker-{{ docker_edition }}.repo

#docker debian repo
docker_apt_release_channel: stable
docker_apt_arch: amd64
docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"

# defaults file for conjurConfig
conjur_version: 'OSS'
conjur_container_name: 'conjur-master'
conjur_network_name: conjur
conjur_https_port: '443'
conjur_cli_container_name: 'conjur-cli'
conjur_cli_image_name: 'cdemo/conjur-cli:latest'
conjur_account: 'cyberark'
conjur_admin_password: 'Cyberark1'
conjur_internal_url: "https://{{ conjur_container_name }}"
conjur_external_url: "https://{{ ansible_default_ipv4.address }}"
conjur_audit_volume: "audit"
conjur_audit_directory: '/var/log/conjur'
conjur_devops_admin_account: "eva"

conjur_OSS_image_name: 'cyberark/conjur'
conjur_OSS_port: '81'
conjur_OSS_url: "http://{{ ansible_default_ipv4.address }}:{{ conjur_OSS_port }}"
conjur_OSS_container_name: 'conjur-oss'
conjur_nginx_image_name: 'cdemo/conjur-nginx:latest'

# defaults file for weavescopeConfig
weavescope_install: 'NO'

# defaults file for gogsconfig
gogs_install: 'NO'
gogs_internal_port: '3000'
gogs_external_port: '10080'
gogs_container_name: 'gogs'
gogs_image_name: 'gogs/gogs'
gogs_internal_url: "http://{{ gogs_container_name }}:{{ gogs_internal_port }}"
gogs_external_url: "http://{{ ansible_default_ipv4.address }}:{{ gogs_external_port }}"

gogs_account: "{{ conjur_devops_admin_account }}"
gogs_account_email: 'eva@cyberark.com'
gogs_account_password: 'Cyberark1'

gogs_organization: 'Cyberark'

# defaults file for jenkinsConfig
jenkins_install: 'NO'
jenkins_port: '8080'
jenkins_url: "http://{{ ansible_default_ipv4.address }}:{{ jenkins_port }}"
jenkins_image_name: 'conjur_jenkins:latest'
jenkins_container_name: 'jenkins'

# defaults file for awxConfig
ansible_install: 'NO'
ansible_port: '6060'
ansible_internal_port: '8052'
ansible_external_url: "http://{{ ansible_default_ipv4.address }}:{{ ansible_port }}"
ansible_external_url_login: "{{ ansible_external_url }}/#/login"
ansible_internal_url: "http://awx_web:{{ ansible_internal_port }}"
ansible_password: 'Cyberark1'
ansible_user: "{{ conjur_devops_admin_account }}"
ansible_organization: 'Cyberark'
ansible_pas: 'NO'
ansible_awx_data_dir: '/ansible/pgdocker'

# defaults file for splunk
splunk_install: 'NO'
splunk_container_name: 'splunk'
splunk_image_name: "{{ splunk_container_name }}/{{ splunk_container_name }}"
splunk_hostname: "{{ splunk_container_name }}"
splunk_external_port: "8000"
splunk_internal_port: "8000"
splunk_account_password: "{{ gogs_account_password }}"
splunk_rest_port: "8089"
splunk_audit_volume: "{{ conjur_audit_volume }}"
splunk_account: "{{ conjur_devops_admin_account }}"
splunk_audit_directory: '/conjur'
