pipeline {
    agent any
   
    stages {
        stage ('Upload new policy') {
            steps {
                sh "docker exec conjur-cli bash -c 'cd /Conjur_Policy && git pull && conjur policy load --replace root root.yml'"
            }
        }
    }
}