pipeline {
    agent any
   
    stages {
        stage ('Create Identity for tomcat contaienrs') {
            steps {
                sh "cd bin && bash hfToken.sh tomcat"
            }
        }
		stage ('Create Identity for webapp containers') {
			steps {
				sh "cd bin && bash hfToken.sh webapp"
			}
		}
		stage ('Create tomcat containers') {
			steps {
				sh "cd bin && bash startContainers.sh tomcat 'secrets/frontend/aws_access_key' 5"
			}
		}
		stage ('Create webapp containers') {
			steps {
				sh "cd bin && bash startContainers.sh webapp 'secrets/frontend/aws_access_key' 5"
			}
		}
    }
}