pipeline {
    agent any
   
    stages {
        stage ('stop Tomcat containers') {
            steps {
                sh "bash stopContainers.sh tomcat"
            }
        }
        stage ('stop WebApp containers') {
            steps {
                sh "bash stopContainers.sh webapp"
            }
        }
    }
}