pipeline {
    agent any

    stages {
        stage ('Stop Ansible containers') {
            steps {
                sh 'docker container rm -f $(docker container ls -f name=cdemo-ansible* -q)'
            }
        }
        stage ('Remove host from Tower') {
            steps {
                sh 'tower-cli config host 192.168.56.3:8080'
                sh 'tower-cli host delete -i conjurIdentity -n cdemo-ansible --insecure'
            }
        }
    }
}
